### ISSUE TITLE
3d openpose dataset

### ISSUE THREAD

**Issue by csmibrahim** [hongsukchoi/Pose2Mesh_RELEASE#53]
Thank you very much for sharing this amazing works and for your detailed atient replies in all issues, from which I learned alot. Could you please direct me if I have 3d openpose dataset how I can use your work?

I did extract x & y from the 3d openpose dataset that I have and kept only coco related keypoints.
I run the code then as 
`python demo/run.py --gpu 0 --input_pose demo/points.npy --joint_set coco`
 but I get error
`Traceback (most recent call last):
  File "demo/run.py", line 239, in <module>
    out = optimize_cam_param(project_net, joint_input, crop_size=virtual_crop_size)
  File "demo/run.py", line 155, in optimize_cam_param
    proj_target_joint_img, trans = j2d_processing(joint_input.copy(), (crop_size, crop_size), bbox1, 0, 0, None)
  File "/home/mibrahim/Pose2Mesh_RELEASE/demo/../lib/aug_utils.py", line 54, in j2d_processing
    center, scale = get_center_scale(bbox)
  File "/home/mibrahim/Pose2Mesh_RELEASE/demo/../lib/coord_utils.py", line 8, in get_center_scale
    x, y, w, h = box_info
TypeError: cannot unpack non-iterable NoneType object
srun: error: node001: task 0: Exited with exit code 1
`

Also is there other way to reconstruct the mesh from the 3d openpose dataset direct?

**Comment by hongsukchoi** [comment]
Hi, the error indicates that `box_info` is None. In some parts of my bbox pre-processing functions,  they return None if they find some irregular input. Please check get_bbox, preprocess_bbox functions and use import pdb; pdb.set_trace() near there to see what is happening
