### ISSUE TITLE
Problem in demo

### ISSUE THREAD

**Issue by alexe1ka** [hongsukchoi/Pose2Mesh_RELEASE#9]
hello
in demo/run.py path to weights set as model_chk_path = './experiment/exp_07-07_23:02:27.03/checkpoint'

i have problems:
Traceback (most recent call last):
  File "/home/alexe1ka/my_experiments/Pose2Mesh_RELEASE/demo/../lib/funcs_utils.py", line 134, in load_checkpoint
    checkpoint = torch.load(checkpoint_dir, map_location='cuda')
  File "/home/alexe1ka/.pyenv/versions/my_env/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/alexe1ka/.pyenv/versions/my_env/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/alexe1ka/.pyenv/versions/my_env/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './experiment/exp_07-07_23:02:27.03/checkpoint/checkpoint0.pth.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexe1ka/my_experiments/Pose2Mesh_RELEASE/demo/run.py", line 130, in <module>
    model, joint_regressor, joint_num, skeleton, graph_L, graph_perm_reverse = get_joint_setting(mesh_model, joint_category=joint_set)
  File "/home/alexe1ka/my_experiments/Pose2Mesh_RELEASE/demo/run.py", line 96, in get_joint_setting
    checkpoint = load_checkpoint(load_dir=model_chk_path)
  File "/home/alexe1ka/my_experiments/Pose2Mesh_RELEASE/demo/../lib/funcs_utils.py", line 137, in load_checkpoint
    raise ValueError("No checkpoint exists!\n", e)
ValueError: ('No checkpoint exists!\n', FileNotFoundError(2, 'No such file or directory'))

Process finished with exit code 1

where i can get this file?

**Comment by hongsukchoi** [comment]
Hi,

you can download the pre-trained model weights as written in here: https://github.com/hongsukchoi/Pose2Mesh_RELEASE#pretrained-model-weights

**Comment by alexe1ka** [comment]
i loaded all files,but in this folder i can't find file /experiment/exp_07-07_23:02:27.03/checkpoint/checkpoint0.pth.tar in this folder
maybe I should change something in the config?

**Comment by hongsukchoi** [comment]
No, you should change the line `/experiment/exp_07-07_23:02:27.03/checkpoint/checkpoint0.pth.tar` to the directory of pretrained Pose2Mesh you downloaded. Not the config.

**Comment by alexe1ka** [comment]
thanks you,i resolve conflict
your code uses for get smpl from 2d skeleton.
may i use your code for getting smpl from 3d skeleton???

**Comment by hongsukchoi** [comment]
Yes, you can get 3D mesh from 3D skeleton using our code. 
Pose2Mesh consists of PoseNet and MeshNet.
MeshNet will be the answer.
